### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by hervedumoulinarc** [ywj7931/Hololens_Image_Based_Texture#1]
Hi, great idee, but I get 1 ERROR in Unity 5.5.0b8 and impossible to build.

Assets/Scripts/TakePicture.cs(87,25): error CS1501: No overload for method `StartPhotoModeAsync' takes `3' arguments

**Comment by ywj7931** [comment]
Does Unity 5.5.0b8 officially support hololens? I am using Unity 5.4.0f3 for hololens
https://unity3d.com/partners/microsoft/hololens

**Comment by hervedumoulinarc** [comment]
It should support it, well it is writen in the forum that it does... Anyway same issue with 5.4.0f3... Maybe Im missing something.

**Comment by ywj7931** [comment]
@hervedumoulinarc Did you follow the Unity hololens build instruction?
https://developer.microsoft.com/en-us/windows/holographic/holograms_100
also make sure add scene/main.scene

**Comment by hervedumoulinarc** [comment]
Thanks I will give a try with this tutorial during the next few days...

**Comment by hervedumoulinarc** [comment]
I tried the tutorial, could you please check Line 87 in the code, there is a "calling" error but I cannot understand it.
Tanks again to help me.

**Comment by ywj7931** [comment]
@hervedumoulinarc I cannot replicate the error, did you set like this, and add the scene/main.scene?

Select File > Build Settings...
Select Windows Store in the Platform list.
Set SDK to Universal 10
Set Build Type to D3D.

**Comment by Jennavee** [comment]
Hey!  Im working in 5.5b10 and I fixed this issue by removing "true" in that line of code.  Now it looks like this 

photoCaptureObj.StartPhotoModeAsync(m_CameraParameters,  OnStartPhotoMode);

**Comment by ywj7931** [comment]
@Jennavee  Thanks! I guess they updated the method, in the Docs, they are still requiring the bool parameter:
https://docs.unity3d.com/550/Documentation/ScriptReference/VR.WSA.WebCam.PhotoCapture.StartPhotoModeAsync.html

**Comment by hervedumoulinarc** [comment]
Thanks @Jennavee and @ywj7931 it is working now. Im still looking how I can take photo... Nothing happening when I say "Photo" and the model doesn't dispatch when I say "Save"...

**Comment by hervedumoulinarc** [comment]
Hi me again :) In unity my image coordinates are not correct, my room looks completely weird, I tried to click on preview material but Nothing change ....

**Comment by hervedumoulinarc** [comment]
My fault I restarted the app and it's working now :)

**Comment by hervedumoulinarc** [comment]
Hi in unity my images coordinates are not correct my room looks no good I tried preview material but it change Nothing, thanks for your time.

**Comment by hervedumoulinarc** [comment]
How can I activate permission for your app ? Seems like the microphone doesn't work.

**Comment by ywj7931** [comment]
in the playersetting when building the app, check hololens unity instruction please

**Comment by hervedumoulinarc** [comment]
Thanks !! Im still trying to make mine working, I still hace one warning in the code, I can deploy but I get an error when executing the app .
Here is the warning : 
Assets\HoloToolkit\SpatialUnderstanding\Scripts\SpatialUnderstanding.cs(53,17): warning CS0162: Unreachable code detected
And the code :
 ` /// Switch used by the entire SpatialUnderstanding module to activate processing.
        /// </summary>
        public bool AllowSpatialUnderstanding
        {
            get
            {
#if UNITY_METRO && !UNITY_EDITOR
                return true;
#endif
                return false;
            }`

**Comment by ywj7931** [comment]
hmm...that should be code of holotoolkit, I seemed to read somewhere that warning is benign, basically that code should tell if you are running in editor or not. Can you put your error meesage?

**Comment by hervedumoulinarc** [comment]
There is no error message either in unity nor visual studio, The app deploy well indeed, but when I launch it from the HoloLens it go "ZZZ" I use unity 5.5 b9.

**Comment by hervedumoulinarc** [comment]
Im trying with Unity 5.5 b11

**Comment by ywj7931** [comment]
you mean the app freezes? did you try say “photo" to take photo? you can try 5.4 hololens version and my original code since thats in which I developed it.
